/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "vendas.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

double *
obtertotalvendasdiarias_1(VendaDiariaArgs *argp, CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTERTOTALVENDASDIARIAS,
		(xdrproc_t) xdr_VendaDiariaArgs, (caddr_t) argp,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ListaProdutos *
listarprodutosmaisvendidos_1(ProdutosMaisVendidosArgs *argp, CLIENT *clnt)
{
	static ListaProdutos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LISTARPRODUTOSMAISVENDIDOS,
		(xdrproc_t) xdr_ProdutosMaisVendidosArgs, (caddr_t) argp,
		(xdrproc_t) xdr_ListaProdutos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
