/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VENDAS_H_RPCGEN
#define _VENDAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct VendaDiariaArgs {
	int filialId;
};
typedef struct VendaDiariaArgs VendaDiariaArgs;

struct ProdutosMaisVendidosArgs {
	int filialId;
	int quantidade;
};
typedef struct ProdutosMaisVendidosArgs ProdutosMaisVendidosArgs;

struct Produto {
	char *nome;
	struct Produto *proximo;
};
typedef struct Produto Produto;

typedef Produto *ListaProdutos;

#define VENDAS_PROG 0x20000001
#define VENDAS_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define OBTERTOTALVENDASDIARIAS 1
extern  double * obtertotalvendasdiarias_1(VendaDiariaArgs *, CLIENT *);
extern  double * obtertotalvendasdiarias_1_svc(VendaDiariaArgs *, struct svc_req *);
#define LISTARPRODUTOSMAISVENDIDOS 2
extern  ListaProdutos * listarprodutosmaisvendidos_1(ProdutosMaisVendidosArgs *, CLIENT *);
extern  ListaProdutos * listarprodutosmaisvendidos_1_svc(ProdutosMaisVendidosArgs *, struct svc_req *);
extern int vendas_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OBTERTOTALVENDASDIARIAS 1
extern  double * obtertotalvendasdiarias_1();
extern  double * obtertotalvendasdiarias_1_svc();
#define LISTARPRODUTOSMAISVENDIDOS 2
extern  ListaProdutos * listarprodutosmaisvendidos_1();
extern  ListaProdutos * listarprodutosmaisvendidos_1_svc();
extern int vendas_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_VendaDiariaArgs (XDR *, VendaDiariaArgs*);
extern  bool_t xdr_ProdutosMaisVendidosArgs (XDR *, ProdutosMaisVendidosArgs*);
extern  bool_t xdr_Produto (XDR *, Produto*);
extern  bool_t xdr_ListaProdutos (XDR *, ListaProdutos*);

#else /* K&R C */
extern bool_t xdr_VendaDiariaArgs ();
extern bool_t xdr_ProdutosMaisVendidosArgs ();
extern bool_t xdr_Produto ();
extern bool_t xdr_ListaProdutos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VENDAS_H_RPCGEN */
