/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vendas.h"

bool_t
xdr_VendaDiariaArgs (XDR *xdrs, VendaDiariaArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->filialId))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ProdutosMaisVendidosArgs (XDR *xdrs, ProdutosMaisVendidosArgs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->filialId))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->quantidade))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Produto (XDR *xdrs, Produto *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->proximo, sizeof (Produto), (xdrproc_t) xdr_Produto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ListaProdutos (XDR *xdrs, ListaProdutos *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (Produto), (xdrproc_t) xdr_Produto))
		 return FALSE;
	return TRUE;
}
