#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "symbolTable.h"
#include "codeGeneration.h"

// Global variables
extern SymTable table;
extern FILE *out_file;
static int label_counter = 0;

// Function to create assembly file preamble
void makePreambule(const char *filename)
{
    // Assembly format header with detailed comments
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "; Assembly code generated from: %s\n", filename);
    fprintf(out_file, "; Generated by UFMT Compiler Lab Project\n");
    fprintf(out_file, "; Author: Wesley Antonio Junior dos Santos\n");
    fprintf(out_file, "; Architecture: x86-64 (64-bit)\n");
    fprintf(out_file, "; Assembler: NASM (Netwide Assembler)\n");
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "\n");

    // External function declarations
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "; External function declarations\n");
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "extern printf                   ; C standard library printf\n");
    fprintf(out_file, "extern scanf                    ; C standard library scanf\n");
    fprintf(out_file, "extern exit                     ; C standard library exit\n");
    fprintf(out_file, "\n");

    // Data section with format strings and variables
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "; Data section - Constants and Variables\n");
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "section .data\n");
    fprintf(out_file, "    ; Format strings for I/O operations\n");
    fprintf(out_file, "    fmt_d:       db \"%%ld\", 0          ; Integer format (no newline)\n");
    fprintf(out_file, "    fmt_f:       db \"%%lf\", 0          ; Float format (no newline)\n");
    fprintf(out_file, "    fmt_s:       db \"%%s\", 0          ; String format (no newline)\n");
    fprintf(out_file, "    fmt_dln:     db \"%%ld\", 10, 0     ; Integer format (with newline)\n");
    fprintf(out_file, "    fmt_fln:     db \"%%lf\", 10, 0     ; Float format (with newline)\n");
    fprintf(out_file, "    fmt_sln:     db \"%%s\", 10, 0      ; String format (with newline)\n");
    fprintf(out_file, "\n");
    fprintf(out_file, "    ; Temporary variables\n");
    fprintf(out_file, "    temp_float:  dq 0.0              ; Temporary for float conversions\n");
    fprintf(out_file, "\n");
    fprintf(out_file, "    ; Program variables\n");
}

// End of data section and beginning of code section
void dumpCodeDeclarationEnd()
{
    fprintf(out_file, "\nsection .text\n");
    fprintf(out_file, "global main\n");
    fprintf(out_file, "\n");
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "; Main program entry point\n");
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "main:\n");
    fprintf(out_file, "    ; Initialize stack frame\n");
    fprintf(out_file, "    push rbp                    ; Save base pointer\n");
    fprintf(out_file, "    mov rbp, rsp                ; Set new base pointer\n");
    fprintf(out_file, "\n");
    fprintf(out_file, "    ; Program execution starts here\n");
}

// Function to create assembly file epilogue
void makeCodeEpilogue(void)
{
    // Add final cleanup code to the existing main function
    fprintf(out_file, "\n");
    fprintf(out_file, "    ; Program cleanup and exit\n");
    fprintf(out_file, "    mov rsp, rbp                ; Restore stack pointer\n");
    fprintf(out_file, "    pop rbp                     ; Restore base pointer\n");
    fprintf(out_file, "    mov rdi, 0                  ; Exit status\n");
    fprintf(out_file, "    call exit                   ; Exit program\n");
    fprintf(out_file, "\n");
    fprintf(out_file, "; ===============================================\n");
    fprintf(out_file, "; End of generated assembly code\n");
    fprintf(out_file, "; ===============================================\n");
}
void makeCodeDeclaration(char *dest, char *identifier, Type type, char *value)
{
    if (type == INTEGER)
    {
        if (value == NULL)
            sprintf(dest, "%s: dq 0\n", identifier);
        else
        {
            int x = atoi(value);
            sprintf(dest, "%s: dq %d\n", identifier, x);
        }
    }
    else if (type == REAL)
    {
        if (value == NULL)
            sprintf(dest, "%s: dq 0.0\n", identifier);
        else
        {
            double x = atof(value);
            sprintf(dest, "%s: dq %f\n", identifier, x);
        }
    }
    else
    {
        printf("error: unknown type\n");
    }
}

int makeCodeAssignment(char *dest, char *id, char *expr)
{
    SymTableEntry *ret = findSymTable(&table, id);
    dest[0] = '\0';

    // Validation already done in the syntactic analyzer
    if (ret->type == INTEGER || ret->type == REAL)
    {
        sprintf(dest + strlen(dest), "%s", expr);
        sprintf(dest + strlen(dest), "pop rbx\n");
        sprintf(dest + strlen(dest), "mov [%s],rbx\n", ret->identifier);
    }
    else
    {
        fprintf(stderr, "Unsupported operation involving string at line %d\n",
                cont_lines);
        return 0;
    }
    return 1;
}

int makeCodeLoad(char *dest, char *id, int ref)
{
    dest[0] = '\0';

    if (ref == 0)
    {
        // It's a numeric literal (integer or float)
        if (strchr(id, '.') != NULL)
        {
            // It's a float number
            double val = atof(id);
            sprintf(dest + strlen(dest), "mov rbx,%ld\n", *(long *)&val);
        }
        else
        {
            // It's an integer number
            sprintf(dest + strlen(dest), "mov rbx,%s\n", id);
        }
        sprintf(dest + strlen(dest), "push rbx\n");
        return 1;
    }

    SymTableEntry *ret = findSymTable(&table, id);
    // Validation already done in the syntactic analyzer

    sprintf(dest + strlen(dest), "mov rbx,[%s]\n", ret->identifier);
    sprintf(dest + strlen(dest), "push rbx\n");
    return 1;
}

void makeCodeAdd(char *dest, char *value)
{
    sprintf(dest + strlen(dest), "%s", value);
    sprintf(dest + strlen(dest), "pop rcx\n");
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "add rbx,rcx\n");
    sprintf(dest + strlen(dest), "push rbx\n");
}

void makeCodeSub(char *dest, char *value)
{
    sprintf(dest + strlen(dest), "%s", value);
    sprintf(dest + strlen(dest), "pop rcx\n");
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "sub rbx,rcx\n");
    sprintf(dest + strlen(dest), "push rbx\n");
}

void makeCodeMul(char *dest, char *value2)
{
    sprintf(dest + strlen(dest), "%s", value2);
    sprintf(dest + strlen(dest), "pop rcx\npop rbx\nimul rbx,rcx\npush rbx\n");
}

void makeCodeDiv(char *dest, char *value2)
{
    sprintf(dest + strlen(dest), "%s", value2);
    sprintf(dest + strlen(dest), "pop r8\n");
    sprintf(dest + strlen(dest), "pop rax\n");
    sprintf(dest + strlen(dest), "xor rdx,rdx\n");
    sprintf(dest + strlen(dest), "idiv r8\n");
    sprintf(dest + strlen(dest), "push rax\n");
}

void makeCodeMod(char *dest, char *value2)
{
    sprintf(dest + strlen(dest), "%s", value2);
    sprintf(dest + strlen(dest), "pop r8\n");
    sprintf(dest + strlen(dest), "pop rax\n");
    sprintf(dest + strlen(dest), "xor rdx,rdx\n");
    sprintf(dest + strlen(dest), "idiv r8\n");
    sprintf(dest + strlen(dest), "push rdx\n");
}

void makeCodeNeg(char *dest)
{
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "neg rbx\n");
    sprintf(dest + strlen(dest), "push rbx\n");
}

// Implementation of new functions for I/O
void makeCodeRead(char *dest, char *varname, Type type)
{
    dest[0] = '\0';
    if (type == INTEGER)
    {
        sprintf(dest + strlen(dest), "    lea rdi, [fmt_d]            ; Integer format\n");
        sprintf(dest + strlen(dest), "    lea rsi, [%s]               ; Variable address\n", varname);
        sprintf(dest + strlen(dest), "    mov rax, 0                  ; Clear rax for scanf\n");
        sprintf(dest + strlen(dest), "    call scanf                  ; Call scanf\n");
    }
    else if (type == REAL)
    {
        sprintf(dest + strlen(dest), "    lea rdi, [fmt_f]            ; Float format\n");
        sprintf(dest + strlen(dest), "    lea rsi, [%s]               ; Variable address\n", varname);
        sprintf(dest + strlen(dest), "    mov rax, 0                  ; Clear rax for scanf\n");
        sprintf(dest + strlen(dest), "    call scanf                  ; Call scanf\n");
    }
}

void makeCodeWrite(char *dest)
{
    sprintf(dest + strlen(dest), "    ; Write operation - integer output\n");
    sprintf(dest + strlen(dest), "    pop rbx                     ; Get value to write\n");
    sprintf(dest + strlen(dest), "    mov rsi, rbx                ; Move to printf argument\n");
    sprintf(dest + strlen(dest), "    lea rdi, [fmt_dln]          ; Load format string\n");
    sprintf(dest + strlen(dest), "    mov rax, 0                  ; Clear rax for printf\n");
    sprintf(dest + strlen(dest), "    call printf                 ; Call printf\n");
}

void makeCodeWriteString(char *dest, char *str)
{
    dest[0] = '\0';
    // Remove quotes from string and create a label for it
    static int string_counter = 0;
    char string_label[64];
    sprintf(string_label, "str_%d", string_counter++);

    // Add string to data section (this should be done in a separate function)
    // For now, we'll use the string directly
    int len = strlen(str);
    char clean_str[len + 1];

    // Remove the quotes
    if (str[0] == '"' && str[len - 1] == '"')
    {
        strncpy(clean_str, str + 1, len - 2);
        clean_str[len - 2] = '\0';
    }
    else
    {
        strcpy(clean_str, str);
    }

    sprintf(dest + strlen(dest), "lea rdi, [fmt_sln]\n");
    sprintf(dest + strlen(dest), "mov rsi, %s\n", clean_str);
    sprintf(dest + strlen(dest), "call printf\n");
}

// Implementation of functions for control structures
void makeCodeIf(char *dest, char *condition, char *body)
{
    int label = label_counter++;
    dest[0] = '\0';

    sprintf(dest + strlen(dest), "%s", condition);
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "cmp rbx, 0\n");
    sprintf(dest + strlen(dest), "je .L%d\n", label);
    sprintf(dest + strlen(dest), "%s", body);
    sprintf(dest + strlen(dest), ".L%d:\n", label);
}

void makeCodeIfElse(char *dest, char *condition, char *ifBody, char *elseBody)
{
    int label1 = label_counter++;
    int label2 = label_counter++;
    dest[0] = '\0';

    sprintf(dest + strlen(dest), "%s", condition);
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "cmp rbx, 0\n");
    sprintf(dest + strlen(dest), "je .L%d\n", label1);
    sprintf(dest + strlen(dest), "%s", ifBody);
    sprintf(dest + strlen(dest), "jmp .L%d\n", label2);
    sprintf(dest + strlen(dest), ".L%d:\n", label1);
    sprintf(dest + strlen(dest), "%s", elseBody);
    sprintf(dest + strlen(dest), ".L%d:\n", label2);
}

void makeCodeWhile(char *dest, char *condition, char *body)
{
    int label1 = label_counter++;
    int label2 = label_counter++;
    dest[0] = '\0';

    sprintf(dest + strlen(dest), ".L%d:\n", label1);
    sprintf(dest + strlen(dest), "%s", condition);
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "cmp rbx, 0\n");
    sprintf(dest + strlen(dest), "je .L%d\n", label2);
    sprintf(dest + strlen(dest), "%s", body);
    sprintf(dest + strlen(dest), "jmp .L%d\n", label1);
    sprintf(dest + strlen(dest), ".L%d:\n", label2);
}

// Implementation of functions for comparisons
void makeCodeComparison(char *dest, char *op)
{
    sprintf(dest + strlen(dest), "pop rcx\n");
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "cmp rbx, rcx\n");

    if (strcmp(op, "<") == 0)
    {
        sprintf(dest + strlen(dest), "setl al\n");
    }
    else if (strcmp(op, ">") == 0)
    {
        sprintf(dest + strlen(dest), "setg al\n");
    }
    else if (strcmp(op, "<=") == 0)
    {
        sprintf(dest + strlen(dest), "setle al\n");
    }
    else if (strcmp(op, ">=") == 0)
    {
        sprintf(dest + strlen(dest), "setge al\n");
    }
    else if (strcmp(op, "==") == 0)
    {
        sprintf(dest + strlen(dest), "sete al\n");
    }
    else if (strcmp(op, "!=") == 0)
    {
        sprintf(dest + strlen(dest), "setne al\n");
    }

    sprintf(dest + strlen(dest), "movzx rbx, al\n");
    sprintf(dest + strlen(dest), "push rbx\n");
}

void makeCodeNot(char *dest)
{
    sprintf(dest + strlen(dest), "pop rbx\n");
    sprintf(dest + strlen(dest), "cmp rbx, 0\n");
    sprintf(dest + strlen(dest), "sete al\n");
    sprintf(dest + strlen(dest), "movzx rbx, al\n");
    sprintf(dest + strlen(dest), "push rbx\n");
}
