/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EX_H_RPCGEN
#define _EX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define ProgMensagem 2
#define VerMensagem 1

#if defined(__STDC__) || defined(__cplusplus)
#define Enviar 1
extern  char ** enviar_1(char **, CLIENT *);
extern  char ** enviar_1_svc(char **, struct svc_req *);
extern int progmensagem_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Enviar 1
extern  char ** enviar_1();
extern  char ** enviar_1_svc();
extern int progmensagem_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EX_H_RPCGEN */
