/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ex.h"

char **
enviar_1_svc(char **argp, struct svc_req *rqstp)
{
	static char *result;
	printf("Mensagem recebida do cliente: %s", *argp);
	char *resposta = "Eu sou o servidor!!";
	result = resposta;
	return &result;
}
