/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "addsub.h"

int *add_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int result;

	printf("Recebi chamado: add %d %d\n", argp->x, argp->y);
	result = argp->x + argp->y;

	return &result;
}

int *sub_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int result;

	printf("Recebi chamado: sub %d %d\n", argp->x, argp->y);
	result = argp->x - argp->y;

	return &result;
}