/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ex.h"
#include <stdio.h>

/*void
progmensagem_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char * enviar_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ProgMensagem, VerMensagem, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
/*

result_1 = enviar_1(&enviar_1_arg, clnt);
if (result_1 == (char **) NULL) {
clnt_perror (clnt, "call failed");
}
#ifndef	DEBUG
clnt_destroy (clnt);
#endif	 /* DEBUG */
/*}*/

int main(int argc, char *argv[])
{
	CLIENT *clnt;
	char *result, *text, *server;

	if (argc != 3)
	{
		fprintf(stderr, "usage:%s host message\n", argv[0]);
		exit(1);
	}
	server = argv[1];
	text = argv[2];

	clnt = clnt_create(server, ProgMensagem, VerMensagem, "udp");

	if (clnt == (CLIENT *)NULL)
	{
		// nao pode estabelecer conexao com o servidor
		printf("Erro clnt_create");
		clnt_pcreateerror(server);
		fflush(stdout);
		exit(1);
	}

	// chamada do metodo enviar no servidor

	result = *(enviar_1(&text, clnt));

	if (result == (char *)NULL)
	{
		// Algum erro acorreu ao se comunicar com o servidor
		printf("Falha RPC");
		clnt_perror(clnt, server);
		exit(1);
	}

	// Sucesso ao realizar a chamada remota

	if (*result == 0)
	{
		// Server nao eh capaz de imprimir sua mensagem
		fprintf(stderr, "%s: pode imprimir sua mensagem\n", argv[0]);
		exit(1);
	}

	// Imprimir mensagem no console

	printf("Mensagem enviada para %s\n", server);
	printf("Mensagem recebida do Servidor:%s\n", result);
	clnt_destroy(clnt);
	exit(0);
}